name: "Backend Developer"
description: "Install Pipeline required for backed developers"
steps:
  setup:
    - name: "check docker version"
      command: "docker --version"
      expectedOutput: "20.10.5"
      failureMessage: "version mismatch"
      continueOnFail: true
    - name: "check java version"
      command: "java --version"
      continueOnFail: false
  tearDown:
    - name: "check version"
      command: "gh --version"
