name: "Backend Developer"
description: "Pipeline required for backed developers"
steps:
  setup:
    - name: "check gh version"
      command: "gh --version"
      abortIfFailed: false
    - name: "check docker version"
      command: "docker--version"
      abortIfFailed: true
    - name: "check java version"
      command: "java --version"
      abortIfFailed: false
  tearDown:
    - name: "check version"
      command: "gh --version"
      abortIfFailed: false
