name: "Backend Developer pipeline"
description: "Pipeline to install all the required artifacts for developers"
steps:
  install gh:
    description: "install gh cli"
    setup:
      - command: "gh --version"
        onFailure: "failed to check gh version"